### ISSUE TITLE
HTTP Issue

### ISSUE THREAD

**Issue by edewaele** [edewaele/nomino#1]
This issue is due to yapafo. When you try to retrieve an OSM object, an error message "Invalid object" appears.

See https://github.com/Cyrille37/yapafo/issues/16

**Comment by Cyrille37** [comment]
Make a fix in Nomino
https://gitorious.org/nomino/nomino/commit/7c92e0922fce80f5527d9a7b57cdd8278be5671c

**Comment by edewaele** [comment]
I could not encounter this bug anymore
