### ISSUE TITLE
les noms en japonais

### ISSUE THREAD

**Issue by Cyrille37** [edewaele/nomino#2]
Ppour les noms en japonais, il y a 3 tags possibles:
- ja, qui est le même que «name» pour les lieux japonais, ou alors une transcription en caractères japonais pour les lieux étrangers
- ja_rm, qui est le nom en caractères latins
- ja_kana, la version japonaise phonétique

L'interface actuelle ne permet de n'entrer que des codes pays à deux lettres, donc pas ces codes supplémentaires.

original message: http://lists.openstreetmap.org/pipermail/talk-fr/2012-December/052285.html

**Comment by edewaele** [comment]
ja_rm and ja_kana were added to the list

It now possible to type language codes up to ten letters

https://gitorious.org/nomino/nomino/commit/bd5a9f2092699b711a5fa982149721c456cd3df0
