### ISSUE TITLE
Lang codes >= 3 not working

### ISSUE THREAD

**Issue by andreadecorte** [edewaele/nomino#5]
Hi, I was testing the possibility to add translation for languages with 3 letter code (for example, name:fur). If I add any 3 letter code, after clicking Save I don't get the corresponding value (nomino behaves as if I didn't add anything), so nothing is uploaded on OSM. If I add also a 2 letter code value (like "it"), I see only the latter value. I tried to take a look at the source code, but I didn't spot any obvious issue... could you please take a look? Thanks and keep up this useful tool!

**Comment by edewaele** [comment]
Hello,

The defect is confirmed. I will try to fix this in the evening.

**Comment by edewaele** [comment]
The issue was fixed. You can check at http://nomino.openstreetmap.fr/

**Comment by andreadecorte** [comment]
Perfect, it works, thanks!
