### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Xuacu** [edewaele/nomino#8]
When I try to log in, authentication process seems to try to log onto www.openstreetmap.orgh (please, note the trailing «h»)
It seems to happen today, yesterday It worked just fine.
Best regards.

**Comment by stefanb** [comment]
This URL probably needs to be fixed in the Nomino application OAuth settings on the www.openstreetmap.org

**Comment by stefanb** [comment]
Workaround: replace " www.openstreetmap.orgh" in the URL with "nomino.openstreetmap.fr", leaving the OAuth parameters in the URL

**Comment by edewaele** [comment]
The OAuth settings seem to be correct.

I could not reproduce this issue.

**Comment by stefanb** [comment]
I noticed it worked fine earlier today & thought you fixed the settings.

**Comment by Xuacu** [comment]
It works fine now for me. Thank you all.
